<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="robots" content="index,follow">



<title>System 7.X - PrintWiki</title>

                <link rel="stylesheet" type="text/css" media="all" href="static/common.css">
                <link rel="stylesheet" type="text/css" media="screen" href="static/layout.css">
                <link rel="stylesheet" type="text/css" media="screen" href="static/style.css">
                

</head>

<body  lang="en" dir="ltr">

<div id="banner">
<table class="logo">
<tr>
<td class="logo_banner">
<a class="nostyle" href="Front_Page"><img align="middle" src="static/printwiki-logo.png" alt="PrintWiki Logo" style="" height="58px" width="192px"></a>
</td>
</tr>
</table>
<div class="tabArea"><a href="Front_Page" class="tab">Front Page</a><a href="Title_Index" class="tab">Title Index</a></div>
</div>
<div id="title">
<table id="title_area_table">
<tr>
<td>
<table id="title_table">
<tr id="iconRow">
<td id="title_text"><h1><a title="System 7.X" class="currentChild" href="System_7.X">System 7.X</a></h1></td>



</tr></table>
</td>
</tr></table></div>



<div id="content" class="content wikipage" lang="en" dir="ltr">
<p id="l1">
The seventh version of the <a title="Macintosh Operating System" href="Macintosh_Operating_System">Macintosh operating system</a>, distinguished by its ability to easily transfer data between different applications and between different users linked to a network, and to address in excess of 128 MB of <a title="RAM" class="nonexistent" href="http://printwiki.org/RAM">RAM</a>. System 7.5 was another major revision of the system (System 7.5.3 is—as of this writing—the most recent re-revision of the system software) that is designed to run with the PowerPC architecture. 
</p>
<div style="clear: both;"></div></div>


<div id="footer"><table width="100%%" border="0" cellspacing="0" cellpadding="0"><tr><td align="left" width="20%"></tr></table></div>

<div class="wikiGlobalFooter" align="center"><div class="wikiSpotFooter">All text and images are licensed under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons License</a><br/> permitting sharing and adaptation with attribution. <br /><br /><strong>PrintWiki – the Free Encyclopedia of Print</strong> <br/> </div></div></body>
</html>

